### ISSUE TITLE
Table overflows in Firefox for Android

### ISSUE THREAD

**Issue by edent** [ukparliament/psephology#1]
Some of the tables look a bit wonky in Firefox 124.2.0 for Android.

https://electionresults.parliament.uk/political-parties/126
![IMG_20240409_035516](https://github.com/ukparliament/psephology/assets/837136/b4feeaf4-e6ea-4f49-8f9d-9259cd0fd3a7)

https://electionresults.parliament.uk/boundary-sets/8/vote-share
![IMG_20240409_035620](https://github.com/ukparliament/psephology/assets/837136/3e52cf29-74e2-447d-82de-66bd5590d438)

Everything else looks pretty swish 😃

**Comment by fantasticlife** [comment]
Hi Terence, thanks to Young Robert, this should - finally - be fixed and tables should scroll on a mobile telephone. We have a similar problem with iframes to load hexmaps etc that we also need to sort out...

**Comment by fantasticlife** [comment]
Adding that Robert and I are both iPhone users, so if you do get chance to test on Android, that would be super :)

**Comment by edent** [comment]
Tested working in Firefox.

Please give Young Robert a biscuit and a pat on the head for a job well done.
